### ISSUE TITLE
URL não reconhecendo "product_name"

### ISSUE THREAD

**Issue by juniopereirab** [fga-eps-mds/2018.2-FGAPP-vendas#10]
<img src= 'https://user-images.githubusercontent.com/17153869/46891455-512e0780-ce40-11e8-931c-2ab42c25725a.png'>

No erro acima, o Django declara que o "product_name" não existe. Sendo que tal variavel está inclusa na models

![image](https://user-images.githubusercontent.com/17153869/46891523-85a1c380-ce40-11e8-887f-b621e9616254.png)

e as migrações estão feitas corretamente pelo manage.py

![image](https://user-images.githubusercontent.com/17153869/46891605-c699d800-ce40-11e8-957e-17ef052f2a08.png)

**Comment by lucasca73** [comment]
isso parece problema de migration... todo problema de coluna não encontrada, quando as models estão certas, é problema de esquema do banco, e quem faz os esquemas são as migrations

```
python manage.py makemigrations
python manage.py migrate
```

**Comment by juniopereirab** [comment]
Então, como foi descrito, eu utilizei tais comandos dentro do docker, e eles me retornaram que não havia nenhuma mudança detectada, e nenhuma migração para ser feita.

**Comment by lucasca73** [comment]
@juniopereirab qual o status da issue?

**Comment by juniopereirab** [comment]
@lucasca73 testei essa mesma url em outro computador, dei git clone no repositório, e tudo mais. Porém nesse outro dispositivo, estava aparecendo que ao invés de "product_name does not exist", dizia "orders_oder does not exist"... Assim que possível mando print

**Comment by lucasca73** [comment]
Foi feita uma atualização no ambiente de desenvolvimento, atualize a dev e dá uma verificada.

**Comment by juniopereirab** [comment]
@lucasca73 foi corrigido com sucesso, após tal atualização.
